"""
提示词模板模块，提供各种场景下的提示词模板
"""

from .rag import (
    DEFAULT_RAG_TEMPLATE,
    ACADEMIC_RAG_TEMPLATE,
    BUSINESS_RAG_TEMPLATE,
    TECHNICAL_RAG_TEMPLATE,
    CONVERSATIONAL_RAG_TEMPLATE,
    SUMMARY_RAG_TEMPLATE
)

__all__ = [
    "DEFAULT_RAG_TEMPLATE",
    "ACADEMIC_RAG_TEMPLATE", 
    "BUSINESS_RAG_TEMPLATE",
    "TECHNICAL_RAG_TEMPLATE",
    "CONVERSATIONAL_RAG_TEMPLATE",
    "SUMMARY_RAG_TEMPLATE"
] 